# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\Parser\ParserInterface: '@app.service.parser.rbk_parser'
    App\Service\WebApi\WebApiInterface: '@app.service.web_api.web_api'

    app.service.parser.rbk_parser:
        class: App\Service\Parser\RbkParser
        arguments:
            - '%env(RBK_URL)%'
            - '@App\Service\WebApi\WebApiInterface'

    app.controller.api.v1.parse_controller:
        class: App\Controller\API\V1\ParseController
        tags:
            - { name: App\Service\Parser\ParserInterface }

    app.service.web_api.web_api:
        class: App\Service\WebApi\WebApi